### ISSUE TITLE
Use protocol CustomStringConvertible's "description" instead of "text"

### ISSUE THREAD

**Issue by BasThomas** [SchoonSauce/SwiftDataStructures#1]
Now, for printing, it seems like you are using a custom implementation through the `text` variable. I think it is better to use the `description` variable exposed in the `CustomStringConvertible` protocol as this allows you to directly print the object - outputting the custom string.

**Comment by AJschoons** [comment]
Thanks for pointing that out, they are all now updated to use the CustomStringConvertible protocol instead of the custom text variable implementation
